[grid]
dim = [50, 50, 1]
sublattices = 2
spin_magnitudes = [1.5, 1.5]
pbc = [true, true, false]

[simulation]
initial_state = "z"
model = "ising"
n_equil = 10000
n_steps = 100000
# Manually specify the list of temperatures (choose one; this takes priority)
# temperatures = []

# If `temperatures` is not provided, generate it automatically using the following range settings
temp_start = 10
temp_end = 80
temp_step = 1

num_threads = 10

[output]
outfile = "result.txt"
energy = true
heat_capacity = true
magnetization = true
susceptibility = true
magnetization_abs = true
susceptibility_abs = true


[[exchange]]
from_sub = 0
to_sub = 1
offsets = [[0, 0, 0], [1, 0, 0], [0, 1, 0]]
strength = 0.0013548


[[exchange]]
from_sub = 1
to_sub = 0
offsets = [[0, 0, 0], [-1, 0, 0], [0, -1, 0]]
strength = 0.0013548
