[grid]
dim = [50, 50, 1]
sublattices = 1
spin_magnitudes = [1.0]
pbc = [true, true, false]

[simulation]
initial_state = "z"
kb = 1
model = "ising"       
n_equil = 10000      
n_steps = 100000
# 手动指定温度列表（二选一，优先使用）
# temperatures = []

# 如果不写temperatures，则用下面区间自动生成
temp_start = 1
temp_end = 3
temp_step = 0.05

num_threads = 20

[output]
outfile = "result.txt"

[[exchange]]
from_sub = 0
to_sub = 0
offsets = [[0, -1, 0], [0, 1, 0], [-1, 0, 0], [1, 0, 0]]
strength = 1.0


